name       : python-docker-py
version    : 3.4.1
release    : 9
source     :
    - https://github.com/docker/docker-py/archive/3.4.1.tar.gz : 116e86bd922b247c890ffc8bf547f17ce6979849a19d8824b8f2b87809ad0757
license    : Apache-2.0
component  : programming.python
summary    : An API client for docker written in Python
description: |
    An API client for docker written in Python
builddeps  :
    - pkgconfig(python3)
    - pip
    - python-setuptools
rundeps    :
    - python-docker-pycreds
    - python-requests
    - python-six
    - python-websocket-client
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
