name       : python-docker-py
version    : 2.2.0
release    : 3
source     :
    - https://github.com/docker/docker-py/archive/2.2.0.tar.gz : 982d7a69cfd9f79d99630363dd18751bebadf55623f3a2fd1451c730107e03d0
license    : APACHE-2.0
component  : programming.python
summary    : An API client for docker written in Python
description: An API client for docker written in Python
builddeps  :
    - pkgconfig(python-3.5)
    - pip
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
