name       : python-docker-py
version    : 4.0.1
release    : 14
source     :
    - https://github.com/docker/docker-py/archive/4.0.1.tar.gz : bd38b91da6f71207a409a245811b0502be7b1d3031d8a4491d47121b24821061
license    : Apache-2.0
component  : programming.python
summary    : An API client for docker written in Python
description: |
    An API client for docker written in Python
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-docker-pycreds
    - python-requests
    - python-six
    - python-websocket-client
build      : |
    %python3_setup
install    : |
    %python3_install
