name       : python-docker-py
version    : 3.7.0
release    : 13
source     :
    - https://github.com/docker/docker-py/archive/3.7.0.tar.gz : 635fcf04dd60d4c1aacc27e8a5e045be3132c046bde01333c1014cc7f0ba5b2a
license    : Apache-2.0
component  : programming.python
summary    : An API client for docker written in Python
description: |
    An API client for docker written in Python
builddeps  :
    - pkgconfig(python3)
    - pip
    - python-setuptools
rundeps    :
    - python-docker-pycreds
    - python-requests
    - python-six
    - python-websocket-client
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
