name       : python-docker-py
version    : 2.6.1
release    : 7
source     :
    - https://github.com/docker/docker-py/archive/2.6.1.tar.gz : 6cca44a1f8fc449769695d2bc85be2971d1f12e34588e326c54c2593fdff1b01
license    : Apache-2.0
component  : programming.python
summary    : An API client for docker written in Python
description: |
    An API client for docker written in Python
builddeps  :
    - pkgconfig(python-3.5)
    - pip
    - python-setuptools
rundeps    :
    - python-docker-pycreds
    - python-requests
    - python-six
    - python-websocket-client
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
