name       : python-docker-py
version    : 3.6.0
release    : 12
source     :
    - https://github.com/docker/docker-py/archive/3.6.0.tar.gz : f755d044eb27c63486fe7dcfef7f1f5500456e23f3142a5b237a0ab504267a22
license    : Apache-2.0
component  : programming.python
summary    : An API client for docker written in Python
description: |
    An API client for docker written in Python
builddeps  :
    - pkgconfig(python3)
    - pip
    - python-setuptools
rundeps    :
    - python-docker-pycreds
    - python-requests
    - python-six
    - python-websocket-client
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
