name       : python-docker-py
version    : 3.5.1
release    : 11
source     :
    - https://github.com/docker/docker-py/archive/3.5.1.tar.gz : 4caa3dacce94a492baf46e47b08e4305ac96bc5ab9e0cb8cfd234cba71a30855
license    : Apache-2.0
component  : programming.python
summary    : An API client for docker written in Python
description: |
    An API client for docker written in Python
builddeps  :
    - pkgconfig(python3)
    - pip
    - python-setuptools
rundeps    :
    - python-docker-pycreds
    - python-requests
    - python-six
    - python-websocket-client
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
