name       : python-docker-py
version    : 3.5.0
release    : 10
source     :
    - https://github.com/docker/docker-py/archive/3.5.0.tar.gz : 9148c5c883ca246adab50611a9589cf0e56e96edb782220783ee84022df1c134
license    : Apache-2.0
component  : programming.python
summary    : An API client for docker written in Python
description: |
    An API client for docker written in Python
builddeps  :
    - pkgconfig(python3)
    - pip
    - python-setuptools
rundeps    :
    - python-docker-pycreds
    - python-requests
    - python-six
    - python-websocket-client
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
