name       : python-docker-py
version    : 2.3.0
release    : 6
source     :
    - https://github.com/docker/docker-py/archive/2.3.0.tar.gz : 56ca8acbe7f7e9cffbfc8e1a2a256ec0fbe322130b1d1ba432865c707fc9f33f
license    : Apache-2.0
component  : programming.python
summary    : An API client for docker written in Python
description: |
    An API client for docker written in Python
builddeps  :
    - pkgconfig(python-3.5)
    - pip
    - python-setuptools
rundeps    :
    - python-docker-pycreds
    - python-requests
    - python-six
    - python-websocket-client
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
