name       : python-docker-py
version    : 5.0.0
release    : 16
source     :
    - https://github.com/docker/docker-py/archive/5.0.0.tar.gz : 07513d7407f1c9a232a2e497714d8083c303afae388d7cadbe47fb973e65b63c
license    : Apache-2.0
component  : programming.python
summary    : An API client for docker written in Python
description: |
    An API client for docker written in Python
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-docker-pycreds
    - python-requests
    - python-six
    - python-websocket-client
build      : |
    %python3_setup
install    : |
    %python3_install
